### ISSUE TITLE
Given the instructions given on your blog, the tests don't pass as expected without unspecified requirements

### ISSUE THREAD

**Issue by alistair-broomhead** [hjwp/book-example#10]
On your blog post at http://www.obeythetestinggoat.com/intermediate-tdd-workshops-in-london-and-portland.html you specified the following steps:

``` bash
git clone https://github.com/hjwp/book-example/ tdd-workshop
cd tdd-workshop
git fetch --tags
git checkout chapter_17
mkvirtualenv --python=python3 tdd-workshop
pip install -r requirements.txt
python manage.py test  # these should all pass
```

This requires that you have `virtualenvwrapper` installed, which isn't an issue but should probably be specified. `selenium` is then missing from the `requirements.txt` at that tag. On installing these requirements the tests then pass as expected.

**Comment by hjwp** [comment]
Thanks Al!  I've updated the instructions on the post.  Your diligence is much appreciated :)
