### ISSUE TITLE
ch05l009 list/views.py example

### ISSUE THREAD

**Issue by Safuya** [hjwp/book-example#13]
The chapter 5 code example is confusing. Any mention of the if statement that I assume is meant to be in there is gone, causing the test to fail. Below is the code.
```python
def home_page(request):
    return render(request, 'home.html', {
        'new_item_text': request.POST['item_text'],
    })
```

I believe this example should be (maybe with some [...] to indicate ommited code):
```python
def home_page(request):
    if request.method == 'POST':
        return render(request, 'home.html', {
                'new_item_text': request.POST['item_text']
        })
    return render(request, 'home.html')
```

Please let me know if this is correct.

**Comment by hjwp** [comment]
The code at that point in the book is not finished - at this point it's basically a mistake. As you'll see, the very next test after listing ch05l009 shows a test failure, after which we fix it by using the .get function.

I agree that you could still use an if branch if you wanted to. It would be more verbose. But it would win on the "explicit is better than implicit" rule.  

In any case, the code for this view will change again before too long!

I'll bear this in mind for the next edition as a possible area to revisit.
