### ISSUE TITLE
Not Found /static  in charter8

### ISSUE THREAD

**Issue by AndyWangfl** [hjwp/book-example#14]
Hi,
I am a new man to study the python web and I'm reading your book. It's a good book. I have a problem that It always can not find /static/*css though I have done as the book charter8, I used django1.9.
my server  is:
server {
    [...]
    location /static {
        lias /home/elspeth/sites/lifeonlive.cn/static;
    }
    [...]
}
my template: base.html is:
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>To-Do lists</title>
    <link href="/static/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="/static/base.css" rel="stylesheet">
</head>
when I access the web. It will appears NOT Found /static/...
I have find some ways used {%static%}'base.css' ,but I don't know why it will appears the problem.
It have confused me a long time, would you help me ?
 Thank you very much.

**Comment by AndyWangfl** [comment]
my template: base.html
"""
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>To-Do lists</title>
    <link href="/static/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="/static/base.css" rel="stylesheet">
</head>
"""

**Comment by AndyWangfl** [comment]
<link href="/static/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="/static/base.css" rel="stylesheet">

**Comment by hjwp** [comment]
Hi there, I'm really sorry but I can't debug issues with the book here.  Can I ask you to re-post your question, either to the mailing list here https://groups.google.com/forum/#!forum/obey-the-testing-goat-book or as a comment on one of the online versions' chapters http://www.obeythetestinggoat.com/pages/book.html
