### ISSUE TITLE
[Chapter 10] Second unit test in tests_models.py makes first one fail

### ISSUE THREAD

**Issue by SvenPetroll** [hjwp/book-example#6]
I'm not sure if this is specific to me, but as soon as the second unit test(258c9dc) is added, the first one fails.

    ======================================================================
    FAIL: test_saving_and_retrieving_items (lists.tests.test_models.ListAndItemModelTest)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "D:\Code\tdd-tut\superlists\lists\tests\test_models.py", line 25, in      test_saving_and_retrieving_items
        self.assertEqual(saved_list, list_)
    AssertionError: <List: List object> != <List: List object> 

I think this is caused by the second test (which is tested first) and the creation of that temporary list in the database. The first test fetches the first list entry (#L21) instead of the one earlier generated (L11).

It only fails when both tests are run in that automatic lexical ordering.

**Comment by hjwp** [comment]
Hi Sven,

In theory django is resetting the database state completely between each test, so each test shouldn't affect the other ones -- unless you're using some kind of non-standard test runner?

**Comment by SvenPetroll** [comment]
I'm using the default test runner from command line, I've following your book from the beginning. This also happened in a later chapter and I could surpress this error either by @skip or deleting the created list manually at the end of the test. I've googled it a bit, but found nothing relevant to this. 

    def test_saving_and_retrieving_items(self):
        for l in List.objects.all():
            print(l.id)
       [...]

I added this at the beginning and this is my output:

    D:\Code\tdd-tut\superlists (master)
    λ python3 manage.py test lists
    Creating test database for alias 'default'...
    .......................1
    2
    3
    F
    ======================================================================
    FAIL: test_saving_and_retrieving_items (lists.tests.test_models.ListAndItemModelTest)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "D:\Code\tdd-tut\superlists\lists\tests\test_models.py", line 28, in     test_saving_and_retrieving_items
        self.assertEqual(saved_list, list_)
    AssertionError: <List: List object> != <List: List object>

    ----------------------------------------------------------------------
    Ran 24 tests in 0.133s

    FAILED (failures=1)
    Destroying test database for alias 'default'...

**Comment by SvenPetroll** [comment]
Oh well, for completeness sake:

I imported `unittest.TestCase` instead of `django.test.TestCase`. Sorry for mixing that up and creating this issue.

**Comment by hjwp** [comment]
:) glad you figured it out!  And hopefully the completeness will help someone else out there... :earth_africa:
