### ISSUE TITLE
Chapter XVIII: Fail test_logged_in_users_lists_are_saved_as_my_lists

### ISSUE THREAD

**Issue by joke2k** [hjwp/book-example#7]
At the line:
https://github.com/hjwp/book-example/blob/chapter_18/functional_tests/test_my_lists.py#L55

This is the stacktrace:
```bash
Traceback (most recent call last):
  File "/workspace/projects/j2k/tdd-book-example/source/functional_tests/test_my_lists.py", line 55, in test_logged_in_users_lists_are_saved_as_my_lists
    []
AssertionError: Lists differ: [<selenium.webdriver.remote.webelement.Web[103 chars]}")>] != []

First list contains 1 additional elements.
First extra element 0:
<selenium.webdriver.remote.webelement.WebElement (session="97d8728c-f84f-4b0e-8aaf-426cae485ec1", element="{6addaa73-957d-485b-a71f-827c94051ced}")>

- [<selenium.webdriver.remote.webelement.WebElement (session="97d8728c-f84f-4b0e-8aaf-426cae485ec1", element="{6addaa73-957d-485b-a71f-827c94051ced}")>]
+ []
```

I fix that with a `time.sleep(3)`

**Comment by hjwp** [comment]
Thanks for reporting this!  This looks like a race condition, where selenium hasn't allowed the page to load properly.  I talk about using "explicit waits" to deal with this sort of problem, in chapter 20 (the continuous integration chapter).

http://chimera.labs.oreilly.com/books/1234000000754/ch20.html#_a_common_selenium_problem_race_conditions

I'll see if I can add a note to chapter 18...
