### ISSUE TITLE
Chapter 5: Fail test_home_page_returns_correct_html

### ISSUE THREAD

**Issue by ckLXHL** [hjwp/book-example#9]
I use django Django (1.9.1)

After I add csrf into template like:
<code>
   \<form method="POST"\>
</code>
       <code> \<input type="text" id="id_new_item" placeholder="Enter a to-do item"/\></code>
       <code> {% csrf_token %}</code>
   <code> \</form\></code>

The testCase test_home_page_returns_correct_html() is failed.
I found the return of render() and render_to_string() is different.
Because render_to_string() don't render the csrf_token but render(request, 'home.html') do.
My solution is add argument of render_to_string like this:
    expected_html = render_to_string('home.html', request=request)
I want know:
is there any better solution to solve this problem? like use this:
<code>
    from django.middleware.csrf import get_token 
</code>
<code>
    csrf_token_value = get_token(request)
</code>

**Comment by dhiraka** [comment]
I have had the same issue and adding the argument "request=request" passed the test. It would be great if the online tutorial is corrected. Thankyou :)

**Comment by hjwp** [comment]
Hi guys, these issues happen if you're running django 1.9.  The book is written for django 1.8 LTS (it's in the installation instructions). Switch back to 1.8 and the issue will go away.

    pip install "django<1.9"
